"""create workflows tables

Revision ID: 665a2dd27798
Revises: b01e9b15ba9d
Create Date: 2025-08-18 11:49:17.513348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665a2dd27798'
down_revision: Union[str, Sequence[str], None] = 'b01e9b15ba9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('logs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'logs')
    # ### end Alembic commands ###
